# database:
#   driver: mysql
#   host: localhost
#   port: 3306
#   username: root
#   password: 274346988@mysql.coM
#   # username: campus_liuyao
#   # password: 274346988@root.coM
#   dbname: campus_wall
#   charset: utf8mb4
#   parseTime: true
#   loc: Local
#   max_idle_conns: 10
#   max_open_conns: 100
#   conn_max_lifetime: 3600

# wechat:
#   appid: wxbec01cd32419625b
#   secret: 3d2aaa51b7befff63ffaea64da2a5c49

# jwt:
#   secret_key: "your-secret-key-here"
#   token_duration: 24h

# database:
#   driver: mysql
#   host: localhost
#   port: 3306
#   username: root
#   password: 274346988@msql.coM
#   dbname: campus_wall
#   charset: utf8mb4
#   parseTime: true
#   loc: Local
#   max_idle_conns: 10
#   max_open_conns: 100
#   conn_max_lifetime: 3600


server:
  port: "8080"
  rate_limit:
    requests: 100  # 每秒请求数
    burst: 200     # 突发请求数
  read_timeout: 10s
  write_timeout: 10s

database:
  driver: "postgres"
  host: "localhost"
  # port: 5432
  port: 3306
  username: "root"
  password: "274346988@mysql.coM"
  dbname: "campus_wall"
  sslmode: "disable"
  parse_time: true

jwt:
  secret_key: "CBk37CK/uj0vQ6nOxV56iCCJbACNLaskWowa5z/ffQk="
  token_duration: 24h

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0
  pool_size: 100
  min_idle_conns: 10
  max_retries: 3
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

logger:
  level: "debug"
  filename: "logs/app.log"
  max_size: 100    # megabytes
  max_backups: 3
  max_age: 28      # days
  compress: true

wechat:
  miniprogram:
    app_id: "wxbec01cd32419625b"
    app_secret: "3d2aaa51b7befff63ffaea64da2a5c49"

storage:
  type: "local"  # 或 "oss"
  local:
    path: "./uploads"
    base_url: "http://localhost:8080/uploads"
  oss:
    endpoint: "oss-cn-beijing.aliyuncs.com"
    access_key_id: "your-access-key-id"
    access_key_secret: "your-access-key-secret"
    bucket_name: "your-bucket-name"